# Generated by Django 4.2 on 2023-11-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SWAPIPeopleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=10)),
                ('mass', models.CharField(max_length=10)),
                ('hair_color', models.CharField(max_length=50)),
                ('skin_color', models.CharField(max_length=50)),
                ('eye_color', models.CharField(max_length=50)),
                ('birth_year', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=20)),
                ('homeworld', models.URLField()),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'SWAPIPerson',
                'verbose_name_plural': 'SWAPIPeople',
                'db_table': 'swapi_people',
            },
        ),
    ]
