# Generated by Django 4.2 on 2023-11-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapipeoplemodel',
            name='date',
            field=models.DateTimeField(default='2014-12-10T13:52:43.172000Z'),
            preserve_default=False,
        ),
    ]
