# Generated by Django 4.2 on 2023-11-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SWAPICollectionDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('download_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'SWAPICollection',
                'verbose_name_plural': 'SWAPICollections',
                'db_table': 'swapi_collections',
            },
        ),
    ]
