CHARACTERS_URL = 'https://swapi.dev/api/people/'
FILMS_URL = 'https://swapi.dev/api/films/'
SPECIES_URL = 'https://swapi.dev/api/species/'
VEHICLES_URL = 'https://swapi.dev/api/vehicles/'
STARSHIPS_URL = 'https://swapi.dev/api/starships/'
